WEATHERFLOW_COLLECTOR_IMPORT_DAYS="365" \
    WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD="SisAdm01" \
    WEATHERFLOW_COLLECTOR_INFLUXDB_URL="http://influxdb01.com:8086/write?db=weatherflow" \
    WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME="idejan" \
    WEATHERFLOW_COLLECTOR_PERF_INTERVAL="60" \
    WEATHERFLOW_COLLECTOR_THREADS="4" \
    WEATHERFLOW_COLLECTOR_TOKEN="a22afsa7-0dcc-4918-9f9a-923dfd339f41c" \
    bash ./generate_docker-compose.sh